import { test, expect } from '@playwright/test'
import fs from 'node:fs/promises'

async function openDisclosure(page, id) {
  const disclosure = page.locator(id)
  if (!(await disclosure.evaluate(element => element.open))) await disclosure.locator(':scope > summary').click()
}

async function setup(page) {
  await page.goto('/')
  await page.setInputFiles('#file-input', 'tests/fixtures/test-tone-8s.wav')
  await expect(page.locator('#export-btn')).toBeEnabled()
  await page.click('[data-mode="lyrics"]')
  await expect(page.locator('#lyrics-source')).toContainText('來源已連結')
  await page.locator('#lyrics-raw').fill('右だけ\n\n右だけ')
  await page.click('[data-command="lyrics.apply"]')
}
async function mark(page, row, start, end) {
  await page.locator(`[data-line="line-${row}"]`).click()
  await page.locator('#lyrics-start-value').fill(String(start)); await page.locator('#lyrics-start-value').press('Tab')
  await page.locator('#lyrics-end-value').fill(String(end)); await page.locator('#lyrics-end-value').press('Tab')
  await page.click('[data-command="lyrics.confirm"]')
}
async function downloaded(page, selector) {
  const pending = page.waitForEvent('download'); await page.click(selector)
  const file = await pending; return fs.readFile(await file.path(), 'utf8')
}
test('lyrics raw text, timing, undo/reopen and four real downloads', async ({ page }, testInfo) => {
  const errors = []; page.on('pageerror', err => errors.push(err.message))
  await setup(page)
  await mark(page, 1, 1, 2); await mark(page, 3, 4, 5)
  await page.click('[data-command="lyrics.undo"]')
  await expect(page.locator('#lyrics-diagnostics')).toContainText('尚未確認')
  await page.click('[data-command="lyrics.redo"]')
  await page.screenshot({ path: testInfo.outputPath('lyrics-desktop.png') })
  const project = await downloaded(page, '[data-command="lyrics.save"]')
  expect(JSON.parse(project).source.hash).toMatch(/^[a-f0-9]{64}$/)
  for (const format of ['txt', 'srt', 'lrc', 'ass']) {
    const text = await downloaded(page, `[data-command="lyrics.export.${format}"]`)
    expect(text).toContain('右だけ')
    if (format === 'txt') expect(text).toBe('右だけ\n\n右だけ')
    if (format === 'srt') expect(text).toContain('00:00:04,000 --> 00:00:05,000')
    if (format === 'lrc') expect(text).toContain('[00:02.00]\n[00:04.00]右だけ')
  }
  await page.reload(); await page.click('[data-mode="lyrics"]')
  await page.setInputFiles('#lyrics-project-file', { name: 'lyrics.json', mimeType: 'application/json', buffer: Buffer.from(project) })
  await expect(page.locator('#lyrics-source')).toContainText('來源未連結')
  await expect(page.locator('[data-command="lyrics.export.srt"]')).toBeDisabled()
  await page.setInputFiles('#file-input', 'tests/fixtures/test-tone-8s.wav')
  await expect(page.locator('#lyrics-source')).toContainText('來源已連結')
  expect(await downloaded(page, '[data-command="lyrics.export.srt"]')).toContain('00:00:04,000 --> 00:00:05,000')
  expect(errors).toEqual([])
})
test('keyboard undo to empty keeps visible focus and restores lyrics with redo', async ({ page }) => {
  await setup(page)
  await page.locator('[data-line="line-1"]').focus()
  await page.keyboard.press('Control+z')
  await expect(page.locator('#lyrics-editor')).toBeHidden()
  await expect(page.locator('#lyrics-original-summary')).toBeFocused()
  await page.keyboard.press('Control+Shift+z')
  await expect(page.locator('#lyrics-editor')).toBeVisible()
  await expect(page.locator('#lyrics-waveform')).toBeFocused()
  await expect(page.locator('#lyrics-raw')).toHaveValue('右だけ\n\n右だけ')
})

test('wrong source, corrupted project, missing timing and IME/input stay recoverable', async ({ page }) => {
  await setup(page); await mark(page, 1, 1, 2)
  await page.click('[data-command="lyrics.export.srt"]')
  await expect(page.locator('#lyrics-status')).toContainText('待打點')
  const project = await downloaded(page, '[data-command="lyrics.save"]')
  await page.setInputFiles('#lyrics-project-file', { name: 'bad.json', mimeType: 'application/json', buffer: Buffer.from('{') })
  await expect(page.locator('#lyrics-status')).toContainText('開啟失敗')
  await expect(page.locator('#lyrics-start-value')).toHaveValue('1')
  await openDisclosure(page, '#lyrics-original')
  await page.locator('#lyrics-raw').fill('a b'); await page.locator('#lyrics-raw').press('End'); await page.locator('#lyrics-raw').press('Space')
  await expect(page.locator('#lyrics-raw')).toHaveValue('a b ')
  await page.setInputFiles('#file-input', 'tests/fixtures/test-tone.wav')
  await expect(page.locator('#lyrics-source')).toContainText('test-tone.wav · 0.500 秒')
  await page.setInputFiles('#lyrics-project-file', { name: 'old.json', mimeType: 'application/json', buffer: Buffer.from(project) })
  await expect(page.locator('#lyrics-source')).toContainText('來源未連結')
  await expect(page.locator('[data-command="lyrics.play"]')).toBeDisabled()
})
test('same-clock sentence loop, source replacement and mobile keyboard controls', async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await setup(page); await mark(page, 1, .1, .3)
  await page.locator('#lyrics-loop').check(); await page.click('[data-command="lyrics.play"]')
  await expect.poll(async () => Number((await page.locator('#lyrics-position').textContent()).split(' ')[0])).toBeGreaterThanOrEqual(.1)
  await expect.poll(async () => Number((await page.locator('#lyrics-position').textContent()).split(' ')[0])).toBeLessThanOrEqual(.3)
  await page.click('[data-command="lyrics.stop"]')
  await page.locator('#lyrics-waveform').focus(); await page.keyboard.press('Home'); await page.keyboard.press('ArrowRight')
  await page.click('[data-command="lyrics.start"]')
  await expect(page.locator('#lyrics-start-value')).toHaveValue('0.1')
  await expect(page.locator('#lyrics-diagnostics')).toContainText('尚未確認')
  await page.locator('#lyrics-end-value').scrollIntoViewIfNeeded()
  await expect(page.locator('#lyrics-end-value')).toBeInViewport()
  await page.locator('[data-command="lyrics.export.txt"]').scrollIntoViewIfNeeded()
  await expect(page.locator('[data-command="lyrics.export.txt"]')).toBeInViewport()
  expect(await page.evaluate(() => scrollX)).toBe(0)
  await page.screenshot({ path: testInfo.outputPath('lyrics-mobile.png') })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})
test('local recovery reconnects the same source without inventing missing timings', async ({ page }) => {
  await setup(page); await mark(page, 1, 1, 2)
  await expect(page.locator('#lyrics-save-status')).toContainText('已備份')
  await page.reload(); await page.click('[data-mode="lyrics"]')
  await page.click('[data-command="lyrics.recover"]')
  await expect(page.locator('#lyrics-source')).toContainText('來源未連結')
  await expect(page.locator('#lyrics-raw')).toHaveValue('右だけ\n\n右だけ')
  await page.setInputFiles('#file-input', 'tests/fixtures/test-tone-8s.wav')
  await expect(page.locator('#lyrics-source')).toContainText('來源已連結')
  await expect(page.locator('#lyrics-start-value')).toHaveValue('1')
  await expect(page.locator('#lyrics-diagnostics')).toContainText('line-3：待打點')
})
test('autosave quota failure preserves editable memory and downloadable project', async ({ page }) => {
  await page.addInitScript(() => {
    const original = Storage.prototype.setItem
    Storage.prototype.setItem = function (key, value) {
      if (key === 'waveforge.lyrics.recovery.v1') throw new DOMException('Quota exceeded', 'QuotaExceededError')
      return original.call(this, key, value)
    }
  })
  await setup(page); await mark(page, 1, 1, 2)
  await expect(page.locator('#lyrics-save-status')).toContainText('備份失敗')
  const project = JSON.parse(await downloaded(page, '[data-command="lyrics.save"]'))
  expect(project.lines[0].start).toBe(1); expect(project.lines[0].confirmed).toBe(true)
  await page.click('[data-command="lyrics.undo"]')
  await expect(page.locator('#lyrics-diagnostics')).toContainText('尚未確認')
})

test('compact lyrics flow discloses setup without hiding consent and restores the master controls on leave', async ({ page }, testInfo) => {
  await page.goto('/')
  await page.click('[data-mode="lyrics"]')
  await expect(page.locator('#lyrics-raw')).toBeVisible()
  await expect(page.locator('#lyrics-editor')).toBeHidden()
  await expect(page.locator('#lyrics-model-settings')).toBeHidden()
  await expect(page.locator('#lyrics-help')).not.toHaveAttribute('open', '')
  await expect(page.locator('.header-actions')).toBeHidden()
  await expect(page.locator('.analysis-bar')).toBeHidden()
  await expect(page.locator('.upload-zone')).toBeVisible()
  await expect(page.locator('#session-privacy')).toBeVisible()
  await expect(page.locator('.transport')).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('lyrics-empty-compact.png') })
  await page.setInputFiles('#file-input', 'tests/fixtures/test-tone-8s.wav')
  await expect(page.locator('#lyrics-source')).toContainText('來源已連結')
  await page.locator('#lyrics-raw').fill('First line\nLast line')
  await page.click('[data-command="lyrics.apply"]')
  await expect(page.locator('#lyrics-raw')).toBeHidden()
  await expect(page.locator('#lyrics-waveform')).toBeVisible()
  await expect(page.locator('#lyrics-list .lyrics-line-text')).toHaveText(['First line', 'Last line'])
  await expect(page.locator('#lyrics-language')).toBeHidden()
  await expect(page.locator('#lyrics-model-info')).toBeVisible()
  await expect(page.locator('#lyrics-model-info')).toContainText('63.3 MiB')
  await expect(page.locator('#lyrics-model-privacy')).toContainText('huggingface.co')
  await expect(page.locator('#lyrics-model-consent')).toBeVisible()
  await expect(page.locator('[data-command="lyrics.align"]')).toBeDisabled()
  const waveform = await page.locator('#lyrics-waveform').boundingBox()
  const setup = await page.locator('#lyrics-alignment').boundingBox()
  expect(waveform.y + waveform.height).toBeLessThan(setup.y)
  await page.screenshot({ path: testInfo.outputPath('lyrics-editing-compact.png') })
  await openDisclosure(page, '#lyrics-model-settings')
  await page.locator('#lyrics-language').selectOption('en')
  await expect(page.locator('[data-command="lyrics.align"]')).toBeDisabled()
  await page.locator('#lyrics-model-settings > summary').click()
  await expect(page.locator('#lyrics-language')).toBeHidden()
  await expect(page.locator('#lyrics-model-consent')).toBeVisible()
  await openDisclosure(page, '#lyrics-original')
  await expect(page.locator('#lyrics-raw')).toHaveValue('First line\nLast line')
  await page.click('[data-mode="master"]')
  await expect(page.locator('.header-actions')).toBeVisible()
  await expect(page.locator('.analysis-bar')).toBeVisible()
  await expect(page.locator('.transport')).toBeVisible()
  await page.click('[data-mode="lyrics"]')
  await expect(page.locator('#lyrics-raw')).toBeVisible()
  await expect(page.locator('#lyrics-raw')).toHaveValue('First line\nLast line')
})

test('390px lyric editor keeps shared playback and touch targets usable', async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await setup(page)
  await expect(page.locator('#lyrics-waveform')).toBeVisible()
  await expect(page.locator('#lyrics-raw')).toBeHidden()
  const controls = page.locator('#mode-lyrics button:visible, #mode-lyrics summary:visible, #mode-lyrics .lyrics-check:visible')
  for (const control of await controls.all()) {
    const box = await control.boundingBox()
    expect(box.height, await control.textContent()).toBeGreaterThanOrEqual(44)
  }
  await page.locator('[data-command="lyrics.export.txt"]').scrollIntoViewIfNeeded()
  const output = await page.locator('[data-command="lyrics.export.txt"]').boundingBox()
  const transport = await page.locator('.transport').boundingBox()
  expect(output.y + output.height).toBeLessThanOrEqual(transport.y)
  await expect(page.locator('#btn-play')).toBeInViewport()
  await expect(page.locator('#time-current')).toBeInViewport()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('lyrics-mobile-compact-tools.png') })
})
