import { readFileSync } from 'node:fs'
import { test, expect } from '@playwright/test'

const audio = name => ({ name, mimeType: 'audio/wav', buffer: readFileSync('tests/fixtures/test-tone.wav') })

test('clear releases source, stems, album and preview, then accepts the same file again', async ({ page }) => {
  const uploads = []
  page.on('request', request => { if (request.method() === 'POST') uploads.push(request.url()) })
  await page.goto('/')
  await page.setInputFiles('#file-input', audio('私密歌曲.wav'))
  await expect(page.locator('#export-btn')).toBeEnabled()
  await page.locator('#album-add-btn').click()
  await page.locator('.final-preview-panel summary').click()
  await page.locator('#final-preview-btn').click()
  await expect(page.locator('#final-preview-download')).toBeVisible()
  const preview = await page.locator('#final-preview-download').getAttribute('href')
  await page.locator('.final-preview-panel summary').click()
  await page.locator('[data-mode="stems"]').click()
  await page.setInputFiles('#stems-local-files', ['人聲', '鼓組', '貝斯', '其他'].map(name => audio(`${name}.wav`)))
  await expect(page.locator('#bounce-btn')).toBeEnabled()
  await page.locator('#session-privacy summary').click()
  await page.locator('#clear-session-btn').click()
  await expect(page.locator('#session-file-status')).toContainText('已清除此頁')
  await expect(page.locator('#export-btn')).toBeDisabled()
  await expect(page.locator('#bounce-btn')).toBeDisabled()
  await expect(page.locator('#album-count')).toHaveText('0 軌')
  await expect(page.locator('#waveform-empty')).toBeAttached()
  await expect(page.locator('#val-bitrate')).toHaveText('—')
  await expect(page.locator('#upload-text-wrap')).not.toContainText('私密歌曲')
  await expect(page.locator('#final-preview-audio')).not.toHaveAttribute('src')
  expect(await page.evaluate(async url => { try { await fetch(url); return true } catch { return false } }, preview)).toBe(false)
  expect(uploads).toEqual([])
  await page.setInputFiles('#file-input', audio('私密歌曲.wav'))
  await expect(page.locator('#export-btn')).toBeEnabled()
  await expect(page.locator('#session-file-status')).toContainText('本頁保留：私密歌曲.wav')
})

test('optional cleanup happens after a valid WAV download', async ({ page }) => {
  await page.goto('/')
  await page.setInputFiles('#file-input', audio('完成後清除.wav'))
  await expect(page.locator('#export-btn')).toBeEnabled()
  await page.locator('#session-privacy summary').click()
  await page.locator('#clear-after-export').check()
  await page.locator('#session-privacy summary').click()
  const downloadPromise = page.waitForEvent('download')
  await page.locator('#export-btn').click()
  const download = await downloadPromise
  expect(download.suggestedFilename()).toBe('完成後清除_master.wav')
  const bytes = readFileSync(await download.path())
  expect(bytes.toString('ascii', 0, 4)).toBe('RIFF')
  expect(bytes.toString('ascii', 8, 12)).toBe('WAVE')
  expect(bytes.length).toBeGreaterThan(1000)
  await expect(page.locator('#export-btn')).toBeDisabled()
  await expect(page.locator('#status-text')).toContainText('已清除此頁音訊')
})
