import { readFileSync } from 'node:fs'
import { beforeEach, afterEach, describe, it, expect, vi } from 'vitest'
import { initDawPanel, formatDawTime, snapDawTime } from '../../src/js/daw/panel.js'
import { sha256Hex } from '../../src/js/audio/sha256.js'
import { encodeWAV } from '../../src/js/audio/wav.js'
import { createProject } from '../../src/js/daw/project.js'
import { createDawDecoder } from '../../src/js/daw/decode.js'
import { initModeNav } from '../../src/js/mode-nav.js'
import { renderProject } from '../../src/js/daw/render.js'
import { exportProjectArchive, importProjectArchive } from '../../src/js/daw/archive.js'

vi.mock('../../src/js/audio/sha256.js', () => ({ sha256Hex: vi.fn(async () => 'a'.repeat(64)) }))
vi.mock('../../src/js/daw/render.js', async importOriginal => ({ ...await importOriginal(), renderProject: vi.fn() }))
vi.mock('../../src/js/daw/archive.js', () => ({
  exportProjectArchive: vi.fn(async () => new Blob(['zip'])),
  importProjectArchive: vi.fn(), archiveFileName: () => 'session.waveforge.zip',
  ARCHIVE_LIMITS: { archiveBytes: 256 * 1024 * 1024, manifestBytes: 1024 * 1024 },
}))
const html = readFileSync('index.html', 'utf8')
const el = id => document.getElementById(`daw-${id}`)
const action = id => document.querySelector(`[data-daw="${id}"]`)
const tick = async () => { for (let i = 0; i < 12; i++) await Promise.resolve() }
const click = async id => { action(id).click(); await tick() }
const change = async (id, value) => { el(id).value = String(value); el(id).dispatchEvent(new Event('change', { bubbles: true })); await tick() }
const makeFile = (name = 'voice.wav') => ({ name, size: 8, arrayBuffer: async () => new ArrayBuffer(8) })
const deferred = () => { let resolve, reject; const promise = new Promise((a, b) => { resolve = a; reject = b }); return { promise, resolve, reject } }
let panel, download, decode, confirm, toMaster
const getBuffer = (seconds = 4) => { const ctx = new AudioContext(); const buffer = ctx.createBuffer(1, seconds * 48000, 48000); buffer.getChannelData(0).fill(.1); return buffer }
async function setup({ importAudio = true, decodeAsset, confirmAction, sendToMaster, AudioContextClass } = {}) {
  const parsed = new DOMParser().parseFromString(html, 'text/html')
  document.body.replaceChildren(parsed.getElementById('app'))
  document.getElementById('mode-editor').hidden = false
  download = vi.fn(); decode = decodeAsset || vi.fn(async () => getBuffer()); confirm = confirmAction || vi.fn(() => true); toMaster = sendToMaster || vi.fn(async () => true)
  panel = initDawPanel({ decodeAsset: decode, confirmAction: confirm, downloadFile: download, onSendToMaster: toMaster, AudioContextClass })
  if (importAudio) await panel.importFiles([makeFile()])
  return panel
}
function clip() { return panel.getProject().tracks[0]?.clips[0] }
function trackChange(field, value) {
  const control = document.querySelector(`[data-track-control="${field}"]`)
  control.value = value; control.dispatchEvent(new Event('change', { bubbles: true })); return tick()
}
beforeEach(() => {
  vi.clearAllMocks()
  renderProject.mockImplementation(async project => ({ buffer: getBuffer(), revision: project.revision, peak: .1, clippedSamples: 0, peaks: { samplePeakDb: -20, truePeakDb: -19.9 } }))
})
afterEach(() => { panel?.destroy(); document.body.replaceChildren(); vi.restoreAllMocks() })

describe('local DAW panel', () => {
  it('keeps the canvas first, details collapsed, and ZIP/loss warnings attached to Save', async () => {
    await setup({ importAudio: false })
    const root = document.getElementById('mode-editor')
    expect(root.querySelector('.daw-heading')).toBeNull()
    expect(el('clip-fields').hidden).toBe(true)
    expect(el('selection-title').textContent).toBe('選取片段以編輯')
    expect(el('help').open).toBe(false)
    expect(el('output-settings').open).toBe(false)
    expect(root.querySelector('.daw-grid-settings').open).toBe(false)
    expect(action('save').getAttribute('aria-describedby')).toBe('daw-save-warning daw-zip-warning')
    expect(el('save-warning').textContent).toContain('不會自動保存')
    expect(el('zip-warning').textContent).toContain('包括裁掉的聲音')
    expect(el('zip-warning').closest('details')).toBeNull()
    expect(el('timeline').compareDocumentPosition(el('help')) & Node.DOCUMENT_POSITION_FOLLOWING).toBeTruthy()
  })
  it('reveals only the selected clip inspector and hides it again when selection disappears', async () => {
    await setup({ importAudio: false })
    await panel.importFiles([makeFile('voice.wav')])
    expect(el('clip-fields').hidden).toBe(false)
    expect(el('selection-title').textContent).toBe('voice.wav')
    expect(el('trim-title').textContent).toBe('保留範圍（時間軸秒數）')
    expect(el('selection-title').textContent).not.toContain('›')
    action('delete').focus()
    await click('delete')
    expect(el('clip-fields').hidden).toBe(true)
    expect(el('clip-fields').disabled).toBe(true)
    expect(document.activeElement).toBe(el('timeline'))
    expect(el('selection-title').textContent).toBe('選取片段以編輯')
    await click('undo')
    document.querySelector('.daw-clip').click()
    expect(el('clip-fields').hidden).toBe(false)
    expect(el('clip-fields').disabled).toBe(false)
  })
  it('renders attacker-controlled media and restored project names only as text', async () => {
    const payload = '<img src=x onerror="globalThis.__wfXss=1"><svg onload="globalThis.__wfXss=1">'
    await setup({ importAudio: false }); await panel.importFiles([makeFile(payload)])
    expect(document.querySelector('.daw-clip-name').textContent).toBe(payload)
    expect(el('selection-title').textContent).toBe(payload)
    expect(document.querySelector('#mode-editor img, #mode-editor svg[onload], #mode-editor [onerror]')).toBeNull()
    const restored = panel.getProject(); restored.name = payload
    importProjectArchive.mockResolvedValueOnce({ project: restored, files: new Map(), buffers: new Map() })
    await panel.openArchive(makeFile('safe.zip'))
    expect(el('name').value).toBe(payload); expect(globalThis.__wfXss).toBeUndefined()
  })
  it('formats time and snaps only positions to the chosen beat grid', () => {
    expect(formatDawTime(65.125)).toBe('01:05.125')
    expect(snapDawTime(.74, 120, 1, true)).toBe(.5)
    expect(snapDawTime(.741, 120, 1, false)).toBe(.741)
  })
  it('imports audio as real tracks and clips; one undo removes a whole batch and redo restores it', async () => {
    await setup({ importAudio: false }); await panel.importFiles([makeFile('voice.wav'), makeFile('beat.wav')])
    expect(panel.getProject().tracks).toHaveLength(2)
    expect(panel.getProject().assets).toHaveLength(2)
    expect(document.querySelectorAll('.daw-wave path')).toHaveLength(2)
    await click('undo'); expect(panel.getProject().tracks).toHaveLength(0)
    await click('redo'); expect(panel.getProject().tracks).toHaveLength(2)
    expect(el('save-state').textContent).toContain('未下載')
  })
  it('binds move, duplicate, trim, split, delete and undo to clip commands', async () => {
    await setup()
    await click('later'); expect(clip().atSeconds).toBe(.5)
    el('snap').checked = false
    await change('clip-at', 1.25); await click('move'); expect(clip().atSeconds).toBe(1.25)
    await change('trim-start', 2); await change('trim-end', 4); await click('trim')
    expect(clip()).toMatchObject({ atSeconds: 2, offsetSeconds: .75, durationSeconds: 2 })
    el('seek').value = '3'; el('seek').dispatchEvent(new Event('input'))
    await click('split'); expect(panel.getProject().tracks[0].clips).toHaveLength(2)
    await click('duplicate'); expect(panel.getProject().tracks[0].clips).toHaveLength(3)
    await click('delete'); expect(panel.getProject().tracks[0].clips).toHaveLength(2)
    await click('undo'); expect(panel.getProject().tracks[0].clips).toHaveLength(3)
  })
  it('retains the selected split clip across duplicate undo/redo and exposes fades through its disclosure', async () => {
    await setup({ importAudio: false }); await panel.importFiles([makeFile('one.wav'), makeFile('two.wav')])
    await click('later'); await change('trim-start', 1); await change('trim-end', 4); await click('trim')
    el('seek').value = '2'; el('seek').dispatchEvent(new Event('input'))
    await click('split')
    const selectedId = document.querySelector('.daw-clip[aria-pressed="true"]').dataset.clipId
    await click('duplicate'); await click('undo'); await click('redo')
    expect(document.querySelectorAll('.daw-clip')).toHaveLength(4)
    expect(document.querySelector('.daw-clip[aria-pressed="true"]').dataset.clipId).toBe(selectedId)
    expect(el('clip-fields').disabled).toBe(false)
    const detail = el('fade-in').closest('details')
    expect(detail.open).toBe(false)
    detail.querySelector('summary').click()
    expect(detail.open).toBe(true)
    await change('fade-in', .05); await change('fade-out', .05); await click('fades')
    const savedClip = panel.getProject().tracks.flatMap(track => track.clips).find(clip => clip.id === selectedId)
    expect(savedClip).toMatchObject({ fadeInSeconds: .05, fadeOutSeconds: .05 })
  })
  it('preserves exact beat positions when trimming at a non-integer-second tempo', async () => {
    await setup(); await change('tempo', 137); await click('later')
    const position = clip().atSeconds
    expect(el('trim-start').value).toBe(String(position))
    await change('trim-end', position + 2); await click('trim')
    expect(clip().durationSeconds).toBeCloseTo(2, 12)
    expect(el('status').dataset.error).toBe('false')
  })
  it('keeps overlapping clips visually selectable on separate rows within the same track', async () => {
    await setup(); await click('duplicate')
    const buttons = [...document.querySelectorAll('.daw-clip')]
    buttons[1].click(); await change('clip-at', 0); await click('move')
    const positions = [...document.querySelectorAll('.daw-clip')].map(item => item.style.top)
    expect(new Set(positions).size).toBe(2)
  })
  it('synchronizes keyboard-focused clips and preserves focus after changing a track control', async () => {
    await setup(); await panel.importFiles([makeFile('second.wav')])
    const firstClip = document.querySelector('.daw-clip')
    firstClip.focus(); firstClip.dispatchEvent(new KeyboardEvent('keydown', { key: 'ArrowRight', bubbles: true })); await tick()
    expect(panel.getProject().tracks[0].clips[0].atSeconds).toBe(.5)
    expect(panel.getProject().tracks[1].clips[0].atSeconds).toBe(0)
    const mute = document.querySelector('[data-track-control="mute"]')
    mute.focus(); mute.click(); await tick()
    expect(document.activeElement.dataset.trackControl).toBe('mute')
  })
  it('moves between tracks while retaining inspector selection', async () => {
    await setup(); await click('add-track')
    const otherId = panel.getProject().tracks[1].id
    await change('clip-track', otherId); await click('move')
    expect(panel.getProject().tracks[1].clips).toHaveLength(1)
    expect(el('clip-fields').disabled).toBe(false)
    await click('later'); expect(panel.getProject().tracks[1].clips[0].atSeconds).toBe(.5)
  })
  it('binds track gain, pan, mute, solo, fades, clip gain and total gain to project metadata', async () => {
    await setup(); await trackChange('gainDb', -3); await trackChange('pan', -.5)
    document.querySelector('[data-track-control="mute"]').click(); await tick()
    document.querySelector('[data-track-control="solo"]').click(); await tick()
    await change('fade-in', .2); await change('fade-out', .3); await click('fades')
    await change('clip-gain', -2); await change('master-gain', -5)
    expect(panel.getProject().tracks[0]).toMatchObject({ gainDb: -3, pan: -.5, mute: true, solo: true })
    expect(clip()).toMatchObject({ gainDb: -2, fadeInSeconds: .2, fadeOutSeconds: .3 })
    expect(panel.getProject().masterGainDb).toBe(-5)
  })
  it('shows validation failure without changing audio state and supports correction', async () => {
    await setup(); const before = panel.getProject()
    await change('fade-in', 3); await change('fade-out', 3); await click('fades')
    expect(panel.getProject()).toEqual(before)
    expect(el('status').dataset.error).toBe('true')
    await change('fade-in', .1); await change('fade-out', .1); await click('fades')
    expect(clip().fadeInSeconds).toBe(.1)
  })
  it('restores canonical displayed values after rejected immediate parameter edits', async () => {
    await setup(); await change('master-gain', 99); await trackChange('gainDb', 99)
    expect(el('master-gain').value).toBe('0')
    expect(document.querySelector('input[data-track-control="gainDb"]').value).toBe('0')
    expect(panel.getProject().masterGainDb).toBe(0)
  })
  it('adds, edits, deletes and resets accessible volume points independently of fades', async () => {
    await setup()
    expect(el('automation-time').readOnly).toBe(true)
    expect(action('automation-remove').disabled).toBe(true)
    expect(action('automation-reset').disabled).toBe(true)
    await change('fade-in', .5); await click('fades')
    await click('automation-add')
    expect(clip().volumeAutomation).toHaveLength(3)
    expect(el('automation-time').readOnly).toBe(false)
    expect(el('automation-point').value).toBe('1')
    expect(document.activeElement).toBe(el('automation-value'))
    await change('automation-time', 1.25); await change('automation-value', 50)
    expect(clip().volumeAutomation[1]).toEqual({ timeSeconds: 2, value: 1 })
    await click('automation-apply')
    expect(clip().volumeAutomation[1]).toEqual({ timeSeconds: 1.25, value: .5 })
    expect(el('automation-graph').querySelector('.daw-automation-line').getAttribute('points')).toBe('16,70 106,97 304,70')
    await click('automation-remove'); expect(clip().volumeAutomation).toHaveLength(2)
    await click('undo'); expect(clip().volumeAutomation).toHaveLength(3)
    await click('redo'); expect(clip().volumeAutomation).toHaveLength(2)
    await click('automation-reset'); expect(clip().volumeAutomation).toBeUndefined()
    expect(clip().fadeInSeconds).toBe(.5)
    await click('undo'); expect(clip().volumeAutomation).toHaveLength(2)
  })
  it('rejects blank, over-limit and unordered automation edits and restores canonical fields', async () => {
    await setup(); await click('automation-add')
    const before = panel.getProject()
    for (const [field, value] of [['automation-value', 201], ['automation-time', 4], ['automation-value', '']]) {
      await change(field, value); await click('automation-apply')
      expect(panel.getProject()).toEqual(before)
      expect(el('status').dataset.error).toBe('true')
      expect(el('automation-value').value).toBe('100')
      expect(el('automation-time').value).toBe('2')
    }
    await change('automation-value', 150); await click('automation-apply')
    expect(clip().volumeAutomation[1].value).toBe(1.5)
    expect(el('status').dataset.error).toBe('false')
  })
  it('commits a whole graph drag once, and cancels Escape/pointercancel/selection changes', async () => {
    await setup(); await click('automation-add')
    const before = panel.getProject()
    vi.spyOn(el('automation-graph'), 'getBoundingClientRect').mockReturnValue({ left: 0, top: 0, width: 320, height: 140 })
    const down = () => el('automation-graph').querySelector('[data-automation-index="1"]').dispatchEvent(new MouseEvent('pointerdown', { bubbles: true, clientX: 160, clientY: 70 }))
    const move = (x = 88, y = 97) => window.dispatchEvent(new MouseEvent('pointermove', { clientX: x, clientY: y }))
    down(); move(100, 80); move()
    expect(panel.getProject()).toEqual(before)
    expect(el('automation-value').value).toBe('50')
    window.dispatchEvent(new MouseEvent('pointerup', { clientX: 88, clientY: 97 })); await tick()
    expect(clip().volumeAutomation[1]).toEqual({ timeSeconds: 1, value: .5 })
    expect(panel.getProject().revision).toBe(before.revision + 1)
    await click('undo'); expect(panel.getProject()).toEqual(before)
    for (const cancellation of ['escape', 'pointercancel', 'selection']) {
      down(); move()
      if (cancellation === 'escape') el('automation-graph').dispatchEvent(new KeyboardEvent('keydown', { key: 'Escape', bubbles: true }))
      else if (cancellation === 'pointercancel') window.dispatchEvent(new Event('pointercancel'))
      else document.querySelector('.daw-clip').click()
      window.dispatchEvent(new MouseEvent('pointerup')); await tick()
      expect(panel.getProject()).toEqual(before)
      expect(el('automation-value').value).toBe('100')
    }
  })
  it('passes edited and split automation to the shared preview/export cache and saves it', async () => {
    await setup(); await click('automation-add'); await change('automation-value', 50); await click('automation-apply')
    await click('play'); await click('play'); await click('export')
    expect(renderProject).toHaveBeenCalledTimes(1)
    expect(renderProject.mock.calls[0][0].tracks[0].clips[0].volumeAutomation[1].value).toBe(.5)
    el('seek').value = '1'; el('seek').dispatchEvent(new Event('input'))
    await click('split'); await click('export')
    expect(renderProject).toHaveBeenCalledTimes(2)
    expect(renderProject.mock.calls[1][0].tracks[0].clips[0].volumeAutomation.at(-1)).toEqual({ timeSeconds: 1, value: .75 })
    await click('save')
    expect(exportProjectArchive.mock.calls[0][0]).toEqual(panel.getProject())
  })
  it('retains automation and original project when amplified output hits the peak guard', async () => {
    await setup(); await change('automation-value', 200); await click('automation-apply')
    const before = panel.getProject()
    renderProject.mockResolvedValueOnce({ buffer: getBuffer(), revision: before.revision, peak: 1.4, clippedSamples: 10, peaks: { samplePeakDb: 2.9, truePeakDb: 3 } })
    await click('export')
    expect(download).not.toHaveBeenCalled()
    expect(el('status').textContent).toContain('停止 WAV 輸出')
    expect(panel.getProject()).toEqual(before)
    await change('master-gain', -6); await click('export')
    expect(download).toHaveBeenCalledOnce()
    expect(clip().volumeAutomation).toEqual(before.tracks[0].clips[0].volumeAutomation)
  })
  it('uses the same renderer result for preview and WAV, then invalidates it on edits', async () => {
    await setup(); await click('play'); await click('play'); await click('export')
    expect(renderProject).toHaveBeenCalledTimes(1)
    expect(download).toHaveBeenCalledWith(expect.any(Blob), '未命名專案-mix.wav')
    await change('sample-rate', 44100); await click('export')
    expect(renderProject).toHaveBeenCalledTimes(2)
    expect(renderProject.mock.calls[1][0].sampleRate).toBe(44100)
  })
  it('blocks integer export on true-peak overload and allows explicit reduced-gain rerender', async () => {
    await setup()
    renderProject.mockResolvedValueOnce({ buffer: getBuffer(), revision: 3, peak: .98, peaks: { samplePeakDb: -.2, truePeakDb: .5 } })
    await click('export'); expect(download).not.toHaveBeenCalled(); expect(el('status').textContent).toContain('降低')
    await change('master-gain', -2); await click('export'); expect(download).toHaveBeenCalledOnce()
  })
  it('passes an audio buffer and explicit revision to mastering', async () => {
    await setup(); await click('master')
    expect(toMaster).toHaveBeenCalledWith(expect.objectContaining({ sampleRate: 48000 }), expect.objectContaining({ name: '未命名專案', revision: panel.getProject().revision, signal: expect.any(AbortSignal), isCurrent: expect.any(Function) }))
  })
  for (const interruption of ['cancel', 'clear', 'leave', 'modify', 'automation', 'undo']) {
    it(`aborts transfer ownership on ${interruption} and never accepts late success`, async () => {
      const pending = deferred(), committed = vi.fn()
      const send = vi.fn(async (_buffer, { signal, isCurrent }) => {
        await pending.promise
        if (signal.aborted || !isCurrent()) throw new DOMException('cancelled', 'AbortError')
        committed()
        return true
      })
      await setup({ sendToMaster: send })
      action('master').click(); await tick()
      expect(send).toHaveBeenCalledOnce()
      const ownership = send.mock.calls[0][1]
      expect(ownership.signal.aborted).toBe(false)
      expect(ownership.isCurrent()).toBe(true)
      if (interruption === 'clear') panel.clear()
      else if (interruption === 'leave') document.dispatchEvent(new CustomEvent('wf:mode-change', { detail: { mode: 'lyrics' } }))
      else if (interruption === 'modify') await change('master-gain', -3)
      else if (interruption === 'automation') await click('automation-add')
      else if (interruption === 'undo') await click('undo')
      else await click('cancel')
      expect(ownership.signal.aborted).toBe(true)
      expect(ownership.isCurrent()).toBe(false)
      pending.resolve(); await tick()
      expect(committed).not.toHaveBeenCalled()
      expect(document.getElementById('mode-editor').hidden).toBe(false)
      expect(el('status').textContent).not.toContain('已將完整混音送往母帶')
    })
  }
  it('navigates to mastering only after successful transfer ownership has retired', async () => {
    const pending = deferred()
    await setup({ sendToMaster: vi.fn(() => pending.promise) })
    const navigation = initModeNav(); navigation.switchMode('editor')
    action('master').click(); await tick()
    const ownership = toMaster.mock.calls[0][1]
    expect(document.getElementById('mode-editor').hidden).toBe(false)
    pending.resolve(true); await tick()
    expect(document.getElementById('mode-master').hidden).toBe(false)
    expect(ownership.signal.aborted).toBe(false)
    expect(action('cancel').hidden).toBe(true)
    expect(el('status').textContent).toContain('已將完整混音送往母帶處理')
  })
  it('does not start hidden playback when resume finishes after leaving the editor', async () => {
    const pending = deferred(), started = vi.fn()
    class DeferredContext {
      constructor() { this.currentTime = 0; this.destination = {} }
      resume() { return pending.promise }
      close() { return Promise.resolve() }
      createBufferSource() { return { connect() {}, disconnect() {}, start: started, stop() {} } }
    }
    await setup({ AudioContextClass: DeferredContext })
    action('play').click(); await tick()
    expect(action('cancel').hidden).toBe(false)
    document.dispatchEvent(new CustomEvent('wf:mode-change', { detail: { mode: 'master' } }))
    pending.resolve(); await tick()
    expect(started).not.toHaveBeenCalled()
    expect(renderProject).not.toHaveBeenCalled()
    expect(action('play').textContent).toBe('播放混音')
    expect(el('status').textContent).not.toContain('正在播放')
  })
  it('uses the same bounded decode hook when restoring a portable project', async () => {
    await setup({ importAudio: false })
    importProjectArchive.mockImplementationOnce(async (_file, options) => {
      const buffer = await options.decodeAsset(new ArrayBuffer(8), { name: 'restored.wav', sampleRate: 48000 }, { signal: options.signal })
      expect(buffer.sampleRate).toBe(48000)
      return { project: createProject(), files: new Map(), buffers: new Map() }
    })
    await panel.openArchive(makeFile('session.waveforge.zip'))
    expect(decode).toHaveBeenCalledWith(expect.any(ArrayBuffer), { name: 'restored.wav', sampleRate: 48000 }, { signal: expect.any(AbortSignal) })
  })
  it('counts original files and retained audio before allocating a long render', async () => {
    await setup({ importAudio: false })
    await panel.importFiles(Array.from({ length: 5 }, (_, i) => ({ ...makeFile(`large-${i}.wav`), size: 64 * 1024 * 1024 })))
    await change('clip-at', 596); await click('move'); await click('export')
    expect(renderProject).not.toHaveBeenCalled()
    expect(el('status').textContent).toContain('記憶體預算')
  })
  it('passes cached mix and retained history memory into archive restoration', async () => {
    await setup(); await click('play'); await click('stop')
    importProjectArchive.mockResolvedValueOnce({ project: createProject(), files: new Map(), buffers: new Map() })
    await panel.openArchive(makeFile('restore.zip'))
    const options = importProjectArchive.mock.calls.at(-1)[1]
    const sourcePCM = 4 * 48000 * 4, cachedPCM = 4 * 48000 * 4
    expect(options.retainedBytes).toBeGreaterThan(sourcePCM + cachedPCM + 8)
  })
  it('includes cached render and retained originals in the archive save budget', async () => {
    await setup({ importAudio: false })
    await panel.importFiles(Array.from({ length: 3 }, (_, i) => ({ ...makeFile(`large-${i}.wav`), size: 64 * 1024 * 1024 })))
    renderProject.mockResolvedValueOnce({ buffer: { length: 20 * 1024 * 1024, numberOfChannels: 2, sampleRate: 48000 }, revision: 9, peak: .1 })
    await click('export') // Cache the render even though its encoded delivery is too large.
    await click('save')
    expect(exportProjectArchive).not.toHaveBeenCalled()
    expect(el('status').textContent).toContain('工程打包')
  })
  it('applies the 24-bit encoding budget before sending a mix to mastering', async () => {
    await setup({ importAudio: false })
    await panel.importFiles(Array.from({ length: 4 }, (_, i) => ({ ...makeFile(`large-${i}.wav`), size: 63 * 1024 * 1024 })))
    renderProject.mockResolvedValueOnce({ buffer: { length: 30 * 1024 * 1024, numberOfChannels: 2, sampleRate: 48000 }, revision: 12, peak: .1 })
    await click('master')
    expect(toMaster).not.toHaveBeenCalled()
    expect(el('status').textContent).toContain('WAV 編碼')
  })
  it('keeps the existing project when a later file in a batch fails decoding', async () => {
    await setup(); const before = panel.getProject()
    decode.mockResolvedValueOnce(getBuffer()).mockRejectedValueOnce(new Error('bad audio'))
    await expect(panel.importFiles([makeFile('valid.wav'), makeFile('bad.wav')])).rejects.toThrow('bad audio')
    expect(panel.getProject()).toEqual(before); expect(el('clip-fields').disabled).toBe(false)
  })
  it('discards a cancelled import even when decoding completes after clear', async () => {
    const pending = deferred(); await setup({ importAudio: false, decodeAsset: () => pending.promise })
    const loading = panel.importFiles([makeFile()]); await tick(); panel.clear(); pending.resolve(getBuffer())
    await expect(loading).rejects.toMatchObject({ name: 'AbortError' })
    expect(panel.getProject().tracks).toHaveLength(0); expect(el('save-state').textContent).toBe('尚無修改')
  })
  it('keeps one ordinary file read owned across repeated cancel and clear', async () => {
    await setup(); const accepted = panel.getProject(), pending = deferred()
    const read = vi.fn(() => pending.promise), nextRead = vi.fn(async () => new ArrayBuffer(8))
    const loading = panel.importFiles([{ ...makeFile('delayed.wav'), size: 64 * 1024 * 1024, arrayBuffer: read }]).catch(error => error)
    await tick(); await click('cancel')
    for (let attempt = 0; attempt < 10; attempt++) {
      await expect(panel.importFiles([{ ...makeFile(), arrayBuffer: nextRead }])).rejects.toThrow(/上一批音檔/)
    }
    expect(read).toHaveBeenCalledTimes(1); expect(nextRead).not.toHaveBeenCalled()
    expect(panel.getProject()).toEqual(accepted)
    panel.clear()
    await expect(panel.importFiles([makeFile()])).rejects.toThrow(/上一批音檔/)
    pending.resolve(new ArrayBuffer(8)); expect(await loading).toMatchObject({ name: 'AbortError' })
    expect(panel.getProject().assets).toHaveLength(0)
    await panel.importFiles([makeFile()]); expect(panel.getProject().assets).toHaveLength(1)
  })
  it('keeps hash work reserved and blocks overlapping restore reads', async () => {
    await setup(); const accepted = panel.getProject(), pending = deferred()
    sha256Hex.mockReturnValueOnce(pending.promise)
    const loading = panel.importFiles([{ ...makeFile('hashing.wav'), size: 64 * 1024 * 1024 }]).catch(error => error)
    await tick(); await click('cancel')
    await expect(panel.openArchive(makeFile('bad.zip'))).rejects.toThrow(/上一批音檔/)
    expect(importProjectArchive).not.toHaveBeenCalled()
    await expect(panel.importFiles([makeFile()])).rejects.toThrow(/上一批音檔/)
    expect(panel.getProject()).toEqual(accepted)
    pending.resolve('a'.repeat(64)); expect(await loading).toMatchObject({ name: 'AbortError' })
    await panel.importFiles([makeFile()]); expect(panel.getProject().assets).toHaveLength(2)
  })
  it('retains cancelled import bytes until the real native decoder settles', async () => {
    const pending = deferred(), source = vi.fn().mockReturnValueOnce(pending.promise).mockResolvedValue(getBuffer())
    class Context { constructor(channels, length, sampleRate) { Object.assign(this, { channels, length, sampleRate }) } }
    const bounded = createDawDecoder({ OfflineAudioContextClass: Context, decodeSource: source })
    await setup({ importAudio: false, decodeAsset: bounded })
    const loading = panel.importFiles([{ ...makeFile(), size: 64 * 1024 * 1024 }]).catch(error => error)
    await tick(); await click('cancel'); expect(await loading).toMatchObject({ name: 'AbortError' })
    panel.clear()
    const read = vi.fn(async () => new ArrayBuffer(8))
    for (let attempt = 0; attempt < 10; attempt++) await expect(panel.importFiles([{ ...makeFile(), arrayBuffer: read }])).rejects.toThrow(/上一批音檔/)
    expect(read).not.toHaveBeenCalled(); expect(source).toHaveBeenCalledTimes(1)
    await expect(panel.openArchive(makeFile('bad.zip'))).rejects.toThrow(/上一批音檔/)
    expect(importProjectArchive).not.toHaveBeenCalled()
    pending.reject(new Error('late native failure')); await tick()
    await panel.importFiles([makeFile()]); expect(source).toHaveBeenCalledTimes(2)
  })
  it('includes cancelled import reservations before starting another render', async () => {
    await setup({ importAudio: false })
    await panel.importFiles(Array.from({ length: 3 }, (_, i) => ({ ...makeFile(`accepted-${i}.wav`), size: 64 * 1024 * 1024 })))
    const pending = deferred()
    const loading = panel.importFiles([{ ...makeFile(), size: 64 * 1024 * 1024, arrayBuffer: () => pending.promise }]).catch(error => error)
    await tick(); await click('cancel')
    await change('clip-at', 496); await click('move'); await click('export')
    expect(renderProject).not.toHaveBeenCalled(); expect(el('status').textContent).toContain('記憶體預算')
    pending.resolve(new ArrayBuffer(8)); expect(await loading).toMatchObject({ name: 'AbortError' })
    await click('play'); expect(renderProject).toHaveBeenCalledTimes(1)
  })
  it('reserves unknown native output against a render started after cancellation', async () => {
    await setup({ importAudio: false })
    await panel.importFiles(Array.from({ length: 3 }, (_, i) => ({ ...makeFile(`accepted-${i}.wav`), size: 64 * 1024 * 1024 })))
    const pending = deferred(); decode.mockReturnValueOnce(pending.promise)
    const loading = panel.importFiles([makeFile('compressed.bin')]).catch(error => error)
    await tick(); await click('cancel'); expect(await loading).toMatchObject({ name: 'AbortError' })
    await change('clip-at', 496); await click('move'); await click('play')
    expect(renderProject).not.toHaveBeenCalled(); expect(el('status').textContent).toContain('記憶體預算')
    pending.resolve(getBuffer()); await tick()
    await click('play'); expect(renderProject).toHaveBeenCalledTimes(1)
  })
  it('counts a cancelled native render after Clear before admitting fresh import reads', async () => {
    const actual = await vi.importActual('../../src/js/daw/render.js')
    const native = deferred(), made = [], nodes = []
    class DelayedContext {
      constructor(channels, frames, sampleRate) { this.destination = {}; made.push({ channels, frames, sampleRate }) }
      node(fields = {}) { const value = { connect() {}, disconnect: vi.fn(), ...fields }; nodes.push(value); return value }
      parameter() { return { setValueAtTime() {}, linearRampToValueAtTime() {} } }
      createGain() { return this.node({ gain: this.parameter() }) }
      createStereoPanner() { return this.node({ pan: this.parameter() }) }
      createBufferSource() { return this.node({ start() {} }) }
      startRendering() { return native.promise }
    }
    await setup(); await change('clip-at', 596); await click('move')
    const accepted = panel.getProject(), plan = actual.buildRenderPlan(accepted)
    renderProject.mockImplementation((project, buffers, options) => actual.renderProject(project, buffers, { ...options, OfflineAudioContextClass: DelayedContext }))
    await click('play'); expect(made).toHaveLength(1)
    const source = nodes.find(node => node.buffer), original = source.buffer, samples = original.getChannelData(0).slice()
    await click('cancel'); panel.clear()
    const read = vi.fn(async () => new ArrayBuffer(8))
    const nextFiles = Array.from({ length: 5 }, (_, index) => ({ ...makeFile(`next-${index}.wav`), size: 64 * 1024 * 1024, arrayBuffer: read }))
    const inputReservation = 7 * 64 * 1024 * 1024
    expect(plan.renderBytes + plan.decodedBytes + inputReservation).toBeGreaterThan(512 * 1024 * 1024)
    try {
      expect(panel.getProject().assets).toHaveLength(0)
      await expect(panel.importFiles(nextFiles)).rejects.toThrow('記憶體預算')
      expect(read).not.toHaveBeenCalled(); expect(source.buffer).toBe(original)
      expect(original.getChannelData(0)).toEqual(samples)
    } finally { native.resolve(null); await tick() }
    await panel.importFiles(nextFiles)
    expect(read).toHaveBeenCalledTimes(5); expect(panel.getProject().assets).toHaveLength(5)
    expect(made).toHaveLength(1)
  })
  it('reserves cancelled ZIP reads, blocks new loads, and preserves accepted PCM', async () => {
    await setup(); await click('play'); await click('stop')
    const accepted = panel.getProject(), acceptedBuffers = renderProject.mock.calls.at(-1)[1]
    const acceptedBuffer = [...acceptedBuffers.values()][0], samples = acceptedBuffer.getChannelData(0).slice()
    const pending = deferred()
    importProjectArchive.mockImplementationOnce(async (_file, options) => {
      options.onMemoryBudget(300 * 1024 * 1024)
      return pending.promise
    })
    const opening = panel.openArchive(makeFile('slow.zip')).catch(error => error)
    await tick(); await click('cancel')
    for (let attempt = 0; attempt < 10; attempt++) {
      await expect(panel.openArchive(makeFile('next.zip'))).rejects.toThrow(/上一批音檔/)
      await expect(panel.importFiles([makeFile()])).rejects.toThrow(/上一批音檔/)
    }
    expect(importProjectArchive).toHaveBeenCalledTimes(1)
    expect(panel.getProject()).toEqual(accepted)
    expect(acceptedBuffer.getChannelData(0)).toEqual(samples)
    // Native late success must never replace the accepted project after Cancel.
    pending.resolve({ project: createProject({ name: 'obsolete' }), files: new Map(), buffers: new Map() })
    expect(await opening).toMatchObject({ name: 'AbortError' })
    expect(panel.getProject()).toEqual(accepted)
    expect(acceptedBuffers.get(accepted.assets[0].id)).toBe(acceptedBuffer)
    expect(acceptedBuffer.getChannelData(0)).toEqual(samples)
    await panel.importFiles([makeFile()]); expect(panel.getProject().assets).toHaveLength(2)
  })
  it('holds ZIP native-decode reservation after prompt cancellation until real settlement', async () => {
    const pending = deferred(), source = vi.fn().mockReturnValueOnce(pending.promise).mockResolvedValue(getBuffer())
    class Context { constructor(channels, length, sampleRate) { Object.assign(this, { channels, length, sampleRate }) } }
    const bounded = createDawDecoder({ OfflineAudioContextClass: Context, decodeSource: source })
    await setup({ importAudio: false, decodeAsset: bounded })
    importProjectArchive.mockImplementationOnce(async (_file, options) => {
      options.onMemoryBudget(300 * 1024 * 1024)
      await options.decodeAsset(new ArrayBuffer(8), {}, { signal: options.signal })
      return { project: createProject(), files: new Map(), buffers: new Map() }
    })
    const opening = panel.openArchive(makeFile('slow.zip')).catch(error => error)
    await tick(); await click('cancel'); expect(await opening).toMatchObject({ name: 'AbortError' })
    panel.clear(); await expect(panel.importFiles([makeFile()])).rejects.toThrow(/上一批音檔/)
    await expect(panel.openArchive(makeFile('again.zip'))).rejects.toThrow(/上一批音檔/)
    pending.resolve(getBuffer()); await tick()
    await panel.importFiles([makeFile()]); expect(source).toHaveBeenCalledTimes(2)
  })
  it('saves originals with project metadata and leaves subsequent edits dirty', async () => {
    await setup(); await click('save')
    expect(exportProjectArchive).toHaveBeenCalledWith(expect.objectContaining({ assets: expect.any(Array) }), expect.any(Map), expect.any(Object))
    expect(el('save-state').textContent).toContain('已交付下載')
    await click('later'); expect(el('save-state').textContent).toContain('未下載')
  })
  it('restores only on successful archive validation and retains old audio on failure', async () => {
    await setup(); const before = panel.getProject()
    importProjectArchive.mockRejectedValueOnce(new Error('invalid archive'))
    await expect(panel.openArchive(makeFile('bad.zip'))).rejects.toThrow('invalid archive')
    expect(panel.getProject()).toEqual(before)
    const restored = createProject({ name: 'Restored' })
    importProjectArchive.mockResolvedValueOnce({ project: restored, files: new Map(), buffers: new Map() })
    await panel.openArchive(makeFile('good.zip'))
    expect(panel.getProject().name).toBe('Restored'); expect(action('undo').disabled).toBe(true)
    expect(importProjectArchive.mock.calls[1][1].retainedBytes).toBeGreaterThan(0)
  })
  it('respects clear/open refusal and warns about unsaved changes before leaving', async () => {
    await setup({ confirmAction: () => false }); const before = panel.getProject()
    await click('clear'); await panel.openArchive(makeFile('session.zip')); expect(panel.getProject()).toEqual(before)
    expect(importProjectArchive).not.toHaveBeenCalled()
    const event = new Event('beforeunload', { cancelable: true }); window.dispatchEvent(event); expect(event.defaultPrevented).toBe(true)
  })
  it('does not let a late render replace a newer edited project', async () => {
    await setup(); const pending = deferred(); renderProject.mockReturnValueOnce(pending.promise)
    action('export').click(); await tick(); await click('later')
    pending.resolve({ buffer: getBuffer(), revision: 3, peak: .1 }); await tick()
    expect(download).not.toHaveBeenCalled(); expect(clip().atSeconds).toBe(.5)
  })
  it('exposes editor mode with accessible tab navigation and hides unrelated master chrome', async () => {
    await setup({ importAudio: false }); const navigation = initModeNav(); navigation.switchMode('editor')
    expect(document.getElementById('app').classList.contains('mode-editor')).toBe(true)
    expect(document.getElementById('mode-master').hidden).toBe(true)
    expect(document.getElementById('tab-editor').getAttribute('aria-selected')).toBe('true')
    expect(document.querySelector('.chain-panel').getAttribute('aria-hidden')).toBe('true')
    const tabs = [...document.querySelectorAll('.mode-tab')]
    const nextTab = tabs[(tabs.indexOf(document.getElementById('tab-editor')) + 1) % tabs.length]
    document.getElementById('tab-editor').dispatchEvent(new KeyboardEvent('keydown', { key: 'ArrowRight', bubbles: true }))
    expect(nextTab.getAttribute('aria-selected')).toBe('true')
    expect(document.getElementById(nextTab.getAttribute('aria-controls')).hidden).toBe(false)
    expect(document.getElementById('mode-editor').hidden).toBe(true)
  })
})


describe('alternate recording replacement: staging, ownership and accepted media', () => {
  it('keeps replacement inside the selected-clip disclosure with warnings beside its chooser and confirmation', async () => {
    await setup({ importAudio: false })
    expect(el('replacement-details').open).toBe(false)
    expect(el('replacement-details').closest('fieldset')).toBe(el('clip-fields'))
    expect(el('clip-fields').hidden).toBe(true)
    expect(action('replace').disabled).toBe(true)
    expect(el('replacement-review').hidden).toBe(true)
    expect(el('zip-warning').textContent).toContain('完整新舊原音')
    await panel.importFiles([makeFile()])
    expect(el('clip-fields').hidden).toBe(false)
    expect(el('replacement-details').open).toBe(false)
    expect(el('current-source').textContent).toContain('voice.wav')
    expect(action('replace').getAttribute('aria-describedby')).toContain('daw-replacement-privacy')
    expect(action('replacement-confirm').getAttribute('aria-describedby')).toContain('daw-replacement-privacy')
    expect(el('replacement-privacy').textContent).toContain('完整新舊錄音')
  })
  it.each(['replacement-cancel', 'replacement-confirm'])('returns keyboard focus to the chooser after %s hides the review', async command => {
    await setup()
    await panel.prepareReplacement(makeFile('candidate.wav'))
    action(command).focus()
    await click(command)
    expect(el('replacement-review').hidden).toBe(true)
    expect(document.activeElement).toBe(action('replace'))
    expect(el('replacement-details').open).toBe(true)
  })
  it('returns keyboard focus to the disclosure when cancelling a pending audition', async () => {
    await setup(); await panel.prepareReplacement(makeFile('candidate.wav'))
    const pending = deferred(); renderProject.mockReturnValueOnce(pending.promise)
    action('replacement-preview').click(); await tick()
    action('replacement-cancel').focus(); await click('replacement-cancel')
    expect(el('replacement-review').hidden).toBe(true)
    expect(document.activeElement).toBe(el('replacement-details').querySelector('summary'))
    pending.resolve({ buffer: getBuffer(), revision: 3, peak: .1 }); await tick()
    expect(action('play').textContent).toBe('播放混音')
  })
  it('sends only the accepted mix to mastering when an unconfirmed replacement exists', async () => {
    await setup(); const before = panel.getProject()
    await panel.prepareReplacement(makeFile('candidate.wav'))
    await click('replacement-preview'); await click('stop')
    await click('master')
    expect(renderProject.mock.calls.at(-1)[0]).toEqual(before)
    expect(toMaster).toHaveBeenCalledOnce()
    expect(toMaster.mock.calls[0][1].revision).toBe(before.revision)
    expect(panel.getProject()).toEqual(before)
  })

  it('shows the exact target and source range, confirms atomically, and restores both sources on undo/redo', async () => {
    await setup()
    await click('later'); await change('trim-start', 1); await change('trim-end', 3); await click('trim')
    await change('clip-gain', -4); await change('fade-in', .25); await click('fades')
    await click('automation-add'); await change('automation-value', 25); await click('automation-apply')
    const before = panel.getProject(), oldClip = clip(), originalId = clip().assetId
    const native = new AudioContext().createBuffer(2, 220500, 44100)
    decode.mockResolvedValueOnce(native)
    await change('replacement-offset', 1.25)
    const file = makeFile('alternate.wav')
    await panel.prepareReplacement(file)
    expect(panel.getProject()).toEqual(before)
    expect(el('replacement-summary').textContent).toContain('alternate.wav（44.1 kHz')
    expect(el('replacement-summary').textContent).toContain('00:01.250–00:03.250')
    expect(el('replacement-review').hidden).toBe(false)
    expect(el('replacement-wave').querySelector('path')).not.toBeNull()
    await click('replacement-confirm')
    const replacementId = clip().assetId
    expect(replacementId).not.toBe(originalId)
    expect(clip()).toEqual({ ...oldClip, assetId: replacementId, offsetSeconds: 1.25 })
    expect(panel.getProject().assets).toHaveLength(2)
    expect(el('replacement-review').hidden).toBe(true)
    await click('play'); await click('stop')
    expect(renderProject.mock.calls.at(-1)[1].get(replacementId)).toBe(native)
    await click('undo'); expect(panel.getProject()).toEqual(before)
    await click('export')
    expect(renderProject.mock.calls.at(-1)[1].has(originalId)).toBe(true)
    await click('redo'); expect(clip().assetId).toBe(replacementId)
    await click('save')
    const [savedProject, savedFiles] = exportProjectArchive.mock.calls.at(-1)
    expect(savedProject.tracks[0].clips[0]).toEqual(clip())
    expect(savedFiles.get(replacementId)).toBe(file)
    expect(savedFiles.has(originalId)).toBe(true)
  })
  it('keeps preview cache separate from ordinary Play, WAV and ZIP until explicit confirmation', async () => {
    await setup(); const before = panel.getProject(), originalId = clip().assetId
    await panel.prepareReplacement(makeFile('candidate.wav'))
    await click('replacement-preview'); await click('stop')
    expect(renderProject.mock.calls[0][0].tracks[0].clips[0].assetId).not.toBe(originalId)
    await click('play'); await click('stop'); await click('export'); await click('save')
    expect(panel.getProject()).toEqual(before)
    expect(renderProject).toHaveBeenCalledTimes(2)
    expect(renderProject.mock.calls[1][0]).toEqual(before)
    expect(exportProjectArchive.mock.calls[0][0]).toEqual(before)
    expect(exportProjectArchive.mock.calls[0][1].size).toBe(1)
    await click('replacement-original'); await click('stop')
    expect(renderProject).toHaveBeenCalledTimes(2)
    await click('replacement-confirm'); await click('export')
    expect(renderProject).toHaveBeenCalledTimes(3)
    expect(renderProject.mock.calls[2][0].tracks[0].clips[0].assetId).not.toBe(originalId)
  })
  it('requires sufficient source range and permits correcting a staged offset without altering the accepted clip', async () => {
    await setup(); const before = panel.getProject()
    decode.mockResolvedValueOnce(getBuffer(2))
    await expect(panel.prepareReplacement(makeFile('short.wav'))).rejects.toThrow('長度不足')
    expect(panel.getProject()).toEqual(before)
    expect(el('replacement-review').hidden).toBe(true)
    decode.mockResolvedValueOnce(getBuffer(5))
    await panel.prepareReplacement(makeFile('long.wav'))
    await change('replacement-offset', 1.01)
    expect(action('replacement-confirm').disabled).toBe(true)
    expect(el('status').textContent).toContain('減少新錄音起點')
    expect(panel.getProject()).toEqual(before)
    await change('replacement-offset', 1)
    expect(action('replacement-confirm').disabled).toBe(false)
    await click('replacement-confirm'); expect(clip().offsetSeconds).toBe(1)
  })
  it('never silently confirms a different offset from the visible unblurred field', async () => {
    await setup(); decode.mockResolvedValueOnce(getBuffer(6))
    await panel.prepareReplacement(makeFile('long.wav'))
    el('replacement-offset').value = '1.5'
    await click('replacement-confirm')
    expect(clip().offsetSeconds).toBe(1.5)
  })
  it.each(['', '-1', 'NaN'])('rejects invalid offset %s without reading a replacement', async value => {
    await setup(); const before = panel.getProject(), file = makeFile()
    file.arrayBuffer = vi.fn(file.arrayBuffer); el('replacement-offset').value = value
    await expect(panel.prepareReplacement(file)).rejects.toThrow('有效')
    expect(file.arrayBuffer).not.toHaveBeenCalled(); expect(panel.getProject()).toEqual(before)
  })
  for (const interruption of ['cancel', 'clear', 'leave', 'selection', 'edit', 'undo', 'automation']) {
    it(`discards a late native decode after ${interruption}, without applying to a different clip`, async () => {
      await setup(); await panel.importFiles([makeFile('second.wav')])
      const before = panel.getProject(), pending = deferred()
      decode.mockReturnValueOnce(pending.promise)
      const work = panel.prepareReplacement(makeFile('late.wav'))
      const assertion = expect(work).rejects.toMatchObject({ name: 'AbortError' })
      await tick()
      if (interruption === 'clear') panel.clear()
      else if (interruption === 'leave') document.dispatchEvent(new CustomEvent('wf:mode-change', { detail: { mode: 'lyrics' } }))
      else if (interruption === 'selection') document.querySelectorAll('.daw-clip')[0].click()
      else if (interruption === 'edit') await change('clip-gain', -3)
      else if (interruption === 'undo') await click('undo')
      else if (interruption === 'automation') await click('automation-add')
      else await click('cancel')
      const after = panel.getProject(); pending.resolve(getBuffer()); await assertion
      expect(panel.getProject()).toEqual(after)
      expect(el('replacement-review').hidden).toBe(true)
      expect(panel.getProject().assets.length).toBeLessThanOrEqual(before.assets.length)
    })
  }
  for (const interruption of ['cancel', 'leave', 'selection', 'edit', 'undo']) {
    it(`discards late replacement mix after ${interruption}`, async () => {
      await setup(); await panel.importFiles([makeFile('second.wav')])
      await panel.prepareReplacement(makeFile('candidate.wav'))
      const pending = deferred(); renderProject.mockReturnValueOnce(pending.promise)
      action('replacement-preview').click(); await tick()
      const options = renderProject.mock.calls[0][2]
      if (interruption === 'leave') document.dispatchEvent(new CustomEvent('wf:mode-change', { detail: { mode: 'lyrics' } }))
      else if (interruption === 'selection') document.querySelectorAll('.daw-clip')[0].click()
      else if (interruption === 'edit') await change('master-gain', -3)
      else if (interruption === 'undo') await click('undo')
      else await click('replacement-cancel')
      expect(options.signal.aborted).toBe(true)
      expect(options.isCurrent()).toBe(false)
      pending.resolve({ buffer: getBuffer(), revision: 123, peak: .1 }); await tick()
      expect(action('play').textContent).toBe('播放混音')
      expect(el('replacement-review').hidden).toBe(true)
    })
  }
  it('captures the selection when opening the file chooser and ignores a late file for another selection', async () => {
    await setup(); await panel.importFiles([makeFile('second.wav')]); const before = panel.getProject()
    await click('replace'); document.querySelectorAll('.daw-clip')[0].click()
    Object.defineProperty(el('replacement-file'), 'files', { value: [makeFile('late-selection.wav')], configurable: true })
    el('replacement-file').dispatchEvent(new Event('change', { bubbles: true })); await tick()
    expect(panel.getProject()).toEqual(before)
    expect(decode).toHaveBeenCalledTimes(2)
    expect(el('replacement-review').hidden).toBe(true)
  })
  it('replacing a staged file cancels its owner and only the newest take can confirm', async () => {
    await setup(); const pending = deferred()
    decode.mockReturnValueOnce(pending.promise).mockResolvedValueOnce(getBuffer())
    const old = panel.prepareReplacement(makeFile('old-candidate.wav'))
    const assertion = expect(old).rejects.toMatchObject({ name: 'AbortError' }); await tick()
    const newest = { ...makeFile('new-candidate.wav'), arrayBuffer: vi.fn(async () => new ArrayBuffer(8)) }
    await expect(panel.prepareReplacement(newest)).rejects.toThrow('背景解碼')
    await assertion; expect(newest.arrayBuffer).not.toHaveBeenCalled()
    pending.resolve(getBuffer()); await tick()
    await panel.prepareReplacement(newest)
    await click('replacement-confirm')
    expect(panel.getProject().assets.at(-1).name).toBe('new-candidate.wav')
    expect(panel.getProject().assets).toHaveLength(2)
  })
  it('retains accepted state on read, hash, decode and PCM failures', async () => {
    await setup(); const before = panel.getProject()
    await expect(panel.prepareReplacement({ ...makeFile(), arrayBuffer: async () => new ArrayBuffer(7) })).rejects.toThrow('不完整')
    sha256Hex.mockRejectedValueOnce(new Error('hash failed'))
    await expect(panel.prepareReplacement(makeFile())).rejects.toThrow('hash failed')
    sha256Hex.mockResolvedValueOnce('short-hash')
    await expect(panel.prepareReplacement(makeFile())).rejects.toThrow('SHA-256')
    decode.mockRejectedValueOnce(new Error('decode failed'))
    await expect(panel.prepareReplacement(makeFile())).rejects.toThrow('decode failed')
    const invalid = getBuffer(); invalid.getChannelData(0)[10] = NaN; decode.mockResolvedValueOnce(invalid)
    await expect(panel.prepareReplacement(makeFile())).rejects.toThrow('non-finite')
    expect(panel.getProject()).toEqual(before)
    await click('save'); expect(exportProjectArchive.mock.calls[0][1].size).toBe(1)
  })
  it('bounds original size and rejects native-rate mismatch without accepting a staged asset', async () => {
    await setup(); const before = panel.getProject(), oversized = { ...makeFile(), size: 64 * 1024 * 1024 + 1 }
    oversized.arrayBuffer = vi.fn(oversized.arrayBuffer)
    await expect(panel.prepareReplacement(oversized)).rejects.toThrow('64 MiB')
    expect(oversized.arrayBuffer).not.toHaveBeenCalled()
    const bytes = encodeWAV([new Float32Array(44100)], 44100, 24)
    await expect(panel.prepareReplacement({ name: 'native.wav', size: bytes.byteLength, arrayBuffer: async () => bytes })).rejects.toThrow('原始取樣率')
    expect(panel.getProject()).toEqual(before)
  })
  it('counts old originals, retained PCM, both A/B render caches and encoding before WAV allocation', async () => {
    await setup({ importAudio: false })
    await panel.importFiles(Array.from({ length: 4 }, (_, i) => ({ ...makeFile(`large-${i}.wav`), size: 64 * 1024 * 1024 })))
    const large = { buffer: { length: 12 * 1024 * 1024, numberOfChannels: 2, sampleRate: 48000 }, revision: 12, peak: .1 }
    renderProject.mockResolvedValue(large)
    await click('play'); await click('stop')
    await panel.prepareReplacement(makeFile('candidate.wav'))
    await click('replacement-preview'); await click('stop')
    expect(renderProject).toHaveBeenCalledTimes(2)
    await click('export')
    expect(download).not.toHaveBeenCalled()
    expect(el('status').textContent).toContain('WAV 編碼會超出')
    expect(panel.getProject().assets).toHaveLength(4)
    await click('replacement-cancel')
    expect(el('replacement-review').hidden).toBe(true)
  })
  it('counts the staged render cache before starting a separate original preview render', async () => {
    await setup({ importAudio: false })
    await panel.importFiles(Array.from({ length: 4 }, (_, i) => ({ ...makeFile(`large-${i}.wav`), size: 64 * 1024 * 1024 })))
    await change('clip-at', 596); await click('move')
    await panel.prepareReplacement(makeFile('candidate.wav'))
    renderProject.mockResolvedValueOnce({ buffer: { length: 25 * 1024 * 1024, numberOfChannels: 2, sampleRate: 48000 }, revision: 14, peak: .1 })
    await click('replacement-preview'); await click('stop')
    expect(renderProject).toHaveBeenCalledOnce()
    await click('replacement-original')
    expect(renderProject).toHaveBeenCalledOnce()
    expect(el('status').textContent).toContain('記憶體預算')
  })
  it('keeps an uncancellable read bounded after Cancel and permits retry only after it settles', async () => {
    await setup(); const before = panel.getProject(), pending = deferred()
    const work = panel.prepareReplacement({ ...makeFile('slow.wav'), arrayBuffer: () => pending.promise })
    const assertion = expect(work).rejects.toMatchObject({ name: 'AbortError' }); await tick()
    await click('cancel')
    const retry = { ...makeFile('new.wav'), arrayBuffer: vi.fn(async () => new ArrayBuffer(8)) }
    await expect(panel.prepareReplacement(retry)).rejects.toThrow('仍在讀取或驗證')
    expect(retry.arrayBuffer).not.toHaveBeenCalled()
    pending.resolve(new ArrayBuffer(8)); await assertion
    await panel.prepareReplacement(retry)
    expect(retry.arrayBuffer).toHaveBeenCalledOnce()
    expect(panel.getProject()).toEqual(before)
  })
  it('blocks new import and ZIP reads while a cancelled replacement read remains owned', async () => {
    await setup(); const before = panel.getProject(), pending = deferred()
    const stage = panel.prepareReplacement({ ...makeFile('pending.wav'), arrayBuffer: () => pending.promise })
    const retired = expect(stage).rejects.toMatchObject({ name: 'AbortError' }); await tick(); await click('cancel')
    const nextFile = { ...makeFile('new.wav'), arrayBuffer: vi.fn(async () => new ArrayBuffer(8)) }
    const decoded = decode.mock.calls.length
    await expect(panel.importFiles([nextFile])).rejects.toThrow('仍在讀取或背景解碼')
    await expect(panel.openArchive(new Blob(['zip']))).rejects.toThrow('仍在讀取或背景解碼')
    expect(nextFile.arrayBuffer).not.toHaveBeenCalled(); expect(decode).toHaveBeenCalledTimes(decoded)
    expect(importProjectArchive).not.toHaveBeenCalled(); expect(panel.getProject()).toEqual(before)
    pending.resolve(new ArrayBuffer(8)); await retired
    await panel.importFiles([nextFile]); expect(nextFile.arrayBuffer).toHaveBeenCalledOnce()
    expect(panel.getProject().assets).toHaveLength(2)
  })
  it('keeps cancelled replacement native ownership through render refusal and Clear until actual decoder settlement', async () => {
    const original = getBuffer(), originalSamples = original.getChannelData(0).slice(), pending = deferred()
    let calls = 0
    const native = vi.fn(() => ++calls === 4 ? pending.promise : Promise.resolve(original))
    const decoder = createDawDecoder({ OfflineAudioContextClass: class {}, decodeSource: native })
    await setup({ importAudio: false, decodeAsset: decoder })
    await panel.importFiles([0, 1, 2].map(i => ({ ...makeFile(`original-${i}.wav`), size: 48 * 1024 * 1024 })))
    await change('clip-at', 596); await click('move')
    const before = panel.getProject(), task = panel.prepareReplacement(makeFile('late.wav'))
    const retired = expect(task).rejects.toMatchObject({ name: 'AbortError' }); await tick()
    expect(native).toHaveBeenCalledTimes(4)
    await click('cancel'); await retired
    expect(panel.getProject()).toEqual(before); expect(original.getChannelData(0)).toEqual(originalSamples)
    const retry = { ...makeFile('retry.wav'), arrayBuffer: vi.fn(async () => new ArrayBuffer(8)) }
    await expect(panel.prepareReplacement(retry)).rejects.toThrow('背景解碼')
    await expect(panel.importFiles([retry])).rejects.toThrow('背景解碼')
    await expect(panel.openArchive(new Blob(['zip']))).rejects.toThrow('背景解碼')
    await click('play'); expect(renderProject).not.toHaveBeenCalled(); expect(el('status').textContent).toContain('記憶體預算')
    panel.clear(); await expect(panel.importFiles([retry])).rejects.toThrow('背景解碼')
    expect(retry.arrayBuffer).not.toHaveBeenCalled(); expect(native).toHaveBeenCalledTimes(4)
    pending.resolve(original); await decoder.whenIdle(); await tick()
    await panel.importFiles([retry]); expect(retry.arrayBuffer).toHaveBeenCalledOnce(); expect(native).toHaveBeenCalledTimes(5)
    expect(panel.getProject().assets).toHaveLength(1); expect(original.getChannelData(0)).toEqual(originalSamples)
    await panel.prepareReplacement(makeFile('ready.wav')); expect(el('replacement-review').hidden).toBe(false)
  })
  it('retires an awaiting hash without decoding or registering after cancellation', async () => {
    await setup(); const before = panel.getProject(), pending = deferred()
    sha256Hex.mockReturnValueOnce(pending.promise)
    const work = panel.prepareReplacement(makeFile('late-hash.wav'))
    const assertion = expect(work).rejects.toMatchObject({ name: 'AbortError' }); await tick()
    await click('cancel'); pending.resolve('f'.repeat(64)); await assertion
    expect(decode).toHaveBeenCalledOnce()
    expect(panel.getProject()).toEqual(before)
    expect(el('replacement-review').hidden).toBe(true)
  })
  it('retains the overload guard after a replacement and permits explicit reduced-gain retry', async () => {
    await setup(); await panel.prepareReplacement(makeFile('loud.wav')); await click('replacement-confirm')
    const before = panel.getProject()
    renderProject.mockResolvedValueOnce({ buffer: getBuffer(), revision: before.revision, peak: 1.2, peaks: { samplePeakDb: 1.6, truePeakDb: 2 } })
    await click('export'); expect(download).not.toHaveBeenCalled()
    expect(panel.getProject()).toEqual(before)
    await change('master-gain', -6); await click('export')
    expect(download).toHaveBeenCalledOnce()
    expect(clip().assetId).toBe(before.tracks[0].clips[0].assetId)
  })
})
