// @vitest-environment node
import { describe, it, expect, vi } from 'vitest'
import { createProject, applyCommand } from '../../src/js/daw/project.js'
import { getDawGridOrigin } from '../../src/js/daw/grid.js'
import { exportProjectArchive, importProjectArchive } from '../../src/js/daw/archive.js'
import { ProjectHistory } from '../../src/js/daw/history.js'
import { buildRenderPlan } from '../../src/js/daw/render.js'
import { createZip } from '../../src/js/audio/zip.js'
import { sha256Hex } from '../../src/js/audio/sha256.js'

const encode = text => new TextEncoder().encode(text)
const decode = bytes => new TextDecoder().decode(bytes)

async function fixture(sampleRate = 44100) {
  const samples = Float32Array.from({ length: 1031 }, (_, index) => Math.sin(index * .173) * .125)
  const bytes = new Uint8Array(samples.buffer)
  const asset = { id: 'synthetic', name: 'synthetic.pcm', hash: await sha256Hex(bytes), sampleRate,
    channels: 1, length: samples.length, duration: samples.length / sampleRate }
  let project = createProject({ assets: [asset], sampleRate })
  project = applyCommand(project, { type: 'track.add', track: { id: 'track' } })
  project = applyCommand(project, { type: 'clip.add', trackId: 'track', clip: {
    id: 'clip', assetId: asset.id, atSeconds: 101 / sampleRate, offsetSeconds: 7 / sampleRate,
    durationSeconds: 997 / sampleRate, fadeInSeconds: 3 / sampleRate, fadeOutSeconds: 11 / sampleRate,
  } })
  const files = new Map([[asset.id, new File([bytes], asset.name, { type: 'application/octet-stream', lastModified: 0 })]])
  const decodeAsset = async raw => ({ sampleRate, length: samples.length, numberOfChannels: 1,
    duration: asset.duration, getChannelData: () => new Float32Array(raw) })
  return { project, files, bytes, decodeAsset }
}

// Only reads the small store-only ZIPs generated by these synthetic fixtures.
async function entriesOf(archive) {
  const bytes = new Uint8Array(await archive.arrayBuffer()), view = new DataView(bytes.buffer)
  const entries = []
  let offset = 0
  while (view.getUint32(offset, true) === 0x04034b50) {
    const length = view.getUint32(offset + 18, true), nameLength = view.getUint16(offset + 26, true)
    const start = offset + 30 + nameLength
    entries.push({ name: decode(bytes.subarray(offset + 30, start)), data: bytes.slice(start, start + length) })
    offset = start + length
  }
  return entries
}

describe('portable grid metadata in local ZIP archives', () => {
  it('restores legacy archives without adding an origin or changing grid phase', async () => {
    const { project, files, decodeAsset } = await fixture()
    const archive = await exportProjectArchive(project, files)
    const restored = await importProjectArchive(archive, { decodeAsset })
    expect(restored.project).toEqual(project)
    expect(restored.project).not.toHaveProperty('gridOriginSeconds')
    expect(getDawGridOrigin(restored.project)).toBe(0)
  })

  it.each([44100, 48000, 96000])('roundtrips fractional origin at %s Hz without changing source bytes or the render recipe', async sampleRate => {
    const { project, files, bytes, decodeAsset } = await fixture(sampleRate)
    const originalPlan = buildRenderPlan(project)
    const saved = applyCommand(project, { type: 'project.update', patch: { tempo: 93.125, gridOriginSeconds: 17 / sampleRate } })
    const archive = await exportProjectArchive(saved, files)
    const entries = await entriesOf(archive)
    expect(JSON.parse(decode(entries[0].data))).toMatchObject({ version: 1, project: { gridOriginSeconds: 17 / sampleRate } })
    expect(entries[1].data).toEqual(bytes)
    const restored = await importProjectArchive(archive, { decodeAsset })
    expect(restored.project).toEqual(saved)
    expect(buildRenderPlan(restored.project)).toEqual({ ...originalPlan, revision: saved.revision })
    expect(new Uint8Array(restored.buffers.get('synthetic').getChannelData(0).buffer)).toEqual(bytes)
    expect(await entriesOf(await exportProjectArchive(restored.project, restored.files))).toEqual(entries)
    const history = new ProjectHistory(restored.project)
    history.push(applyCommand(restored.project, { type: 'project.update', patch: { gridOriginSeconds: 0 } }))
    expect(history.undo()).toEqual(saved)
    expect(history.redo().gridOriginSeconds).toBe(0)
  })

  it('retains a 600-second origin in an empty archive independently of duration', async () => {
    const project = createProject({ gridOriginSeconds: 600 })
    const archive = await exportProjectArchive(project, new Map())
    const restored = await importProjectArchive(archive)
    expect(restored.project).toEqual(project)
    expect(restored.buffers.size).toBe(0)
    expect(getDawGridOrigin(restored.project)).toBe(600)
  })

  it.each(['null', '"0.137"', 'false', '{}', '[]', '-0.1', '600.000001', '1e309', '{"__proto__":{"value":1}}'])('rejects untrusted origin %s before decoding original media', async raw => {
    const { project, files, decodeAsset } = await fixture()
    const saved = applyCommand(project, { type: 'project.update', patch: { gridOriginSeconds: .137 } })
    const entries = await entriesOf(await exportProjectArchive(saved, files))
    entries[0].data = encode(decode(entries[0].data).replace('"gridOriginSeconds":0.137', `"gridOriginSeconds":${raw}`))
    const decoder = vi.fn(decodeAsset)
    await expect(importProjectArchive(new Blob([createZip(entries)]), { decodeAsset: decoder })).rejects.toThrow()
    expect(decoder).not.toHaveBeenCalled()
    expect(project).not.toHaveProperty('gridOriginSeconds')
  })

  it('rejects a prototype attempt beside a valid origin before media decoding', async () => {
    const { project, files, decodeAsset } = await fixture()
    const entries = await entriesOf(await exportProjectArchive(project, files))
    entries[0].data = encode(decode(entries[0].data).replace('"project":{', '"project":{"gridOriginSeconds":1,"__proto__":{"gridOriginSeconds":2},'))
    const decoder = vi.fn(decodeAsset)
    await expect(importProjectArchive(new Blob([createZip(entries)]), { decodeAsset: decoder })).rejects.toThrow(/Unsafe/)
    expect(decoder).not.toHaveBeenCalled()
    expect({}.gridOriginSeconds).toBeUndefined()
  })
})
